config/routes.rb
Rails.application.routes.draw do
  root :to => 'ticket#index'

  resources :admin, :ticket
  post "create_ticket_post" => "ticket#create_ticket_post"
  get "search_ticket" => "ticket#search_ticket"
  get "ticket" => "ticket#ticket"
  post "ticket_add_message_post" => "ticket#ticket_add_message_post"
  post "get_ownership" => "ticket#get_ownership"
  get "admin" => "admin#admin"
  post "log_in_post" => "admin#log_in_post"
  get "tickets" => "admin#tickets"
  post "log_out_post" => "admin#log_out_post"
  get "get_json_tickets" => "admin#get_json_tickets"
  get "tickets_list_partial" => "admin#tickets_list_partial"

  get "users" => "admin#users"
  post "create_user" => "admin#create_user"
  get "get_user" => "admin#get_user"
  post "edit_user" => "admin#edit_user"
  post "delete_user" => "admin#delete_user"

  get "departments" => "admin#departments"
  post "create_department" => "admin#create_department"
  get "get_department" => "admin#get_department"
  post "edit_department" => "admin#edit_department"
  post "delete_department" => "admin#delete_department"

  get "ticket_statuses" => "admin#ticket_statuses"
  post "create_ticket_status" => "admin#create_ticket_status"
  get "get_ticket_status" => "admin#get_ticket_status"
  post "edit_ticket_status" => "admin#edit_ticket_status"
  post "delete_ticket_status" => "admin#delete_ticket_status"
end

app/views/admin/admin.html.haml
%div{:class => ['well', 'centered'], :style => 'width: 400px; height: 230px'}
  = form_tag log_in_post_path, :method => :post do
    #login_label
      = label_tag 'login:'
    #login
      = text_field_tag 'login', '', {:size => '30'}
    %br
    #password_label
      = label_tag 'password:'
    #password
      = password_field_tag 'password', '', {:size => '30'}
    %br
    = submit_tag 'Log in', :class => 'btn btn-success'

app/views/admin/departments.html.haml
%div{:class => 'well centered'}
  %h1 Departments
  %br
  #table{:style => 'border-radius: 25px; padding: 20px; background: #B8E6B8;'}
    %table{:id => "table_id", :class => "display"}
      %thead
        %tr
          %th ID
          %th Department
      %tbody
        -@departments.each do |dep|
          %tr
            %td= dep[:id]
            %td= dep[:title]

#dialog{:style => 'display: none; text-align: center'}
  #title_label
  = label_tag 'Title:'
  %br
  = text_field_tag 'title', '', {:size => '30'}


#confirm{:style => 'display: none; text-align: center'}
  #message Delete department?
#error{:style => 'display: none; text-align: center'}
  #message

:javascript
    $(document).ready( function () {
      $.fn.dataTable.TableTools.defaults.aButtons = [ "div", "div", "div" ];

      var table = $("#table_id").DataTable({
        "aLengthMenu": [5, 10, 15],
        "iDisplayLength": 5,
        "columnDefs": [
          {
              "targets": [0],
              "visible": false
          }
        ],
        "order": [[ 1, "asc" ]],
        "sDom": 'T<"clear">lfrtip',
        "oTableTools": {
            "aButtons": [
                {
                    "sExtends":    "div",
                    "sButtonText": "New department"
                },
                {
                    "sExtends":    "div",
                    "sButtonText": "Edit department"
                },
                {
                    "sExtends":    "div",
                    "sButtonText": "Delete department"
                }
            ]
        }
      });

      table.page(parseInt("#{params[:page] || 0}")).draw(false);

      $('#ToolTables_table_id_1').addClass('DTTT_disabled');
      $('#ToolTables_table_id_2').addClass('DTTT_disabled');

      $('#table_id tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
            $('#ToolTables_table_id_1').addClass('DTTT_disabled');
            $('#ToolTables_table_id_2').addClass('DTTT_disabled');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
            $('#ToolTables_table_id_1').removeClass('DTTT_disabled');
            $('#ToolTables_table_id_2').removeClass('DTTT_disabled');
        }
      } );

      $('#ToolTables_table_id_0').click( function () {
        $('#dialog').dialog({
          width: 370,
          closeText: "",
          modal: true,
          resizable: false,
          title: "New department",
          buttons: [
            {
              text: "Create",
              click: function() {
                $.ajax({
                  method: 'POST',
                  url: "#{create_department_path}",
                  data: {title: $('#title').val()},
                  success: function() {
                    $('#dialog' ).dialog( "close" );
                    window.location.replace("#{departments_path}" + '?page=' + table.page());
                  }
                });
              }
            },
            {
              text: "Cancel",
              click: function() {
                $('#dialog' ).dialog( "close" );
              }
            }
          ]
        });
      } );

      $('#ToolTables_table_id_1').click( function () {
        if(!$('#ToolTables_table_id_1').hasClass('DTTT_disabled')) {
          $.ajax({
            method: 'get',
            url: "#{get_department_path}",
            data: {id: table.row('.selected').data()[0]},
            success: function(json) {
              var data = JSON.parse(json);
              $('#title').val(data.title);
              $('#dialog').dialog({
                width: 370,
                closeText: "",
                modal: true,
                resizable: false,
                title: "Edit department",
                buttons: [
                  {
                    text: "Save",
                    click: function() {
                      $.ajax({
                        method: 'POST',
                        url: "#{edit_department_path}",
                        data: {id: data.id, title: $('#title').val()},
                        success: function() {
                          $('#dialog' ).dialog( "close" );
                          window.location.replace("#{departments_path}" + '?page=' + table.page());
                        }
                      });
                    }
                  },
                  {
                    text: "Cancel",
                    click: function() {
                      $('#dialog' ).dialog( "close" );
                    }
                  }
                ]
              });
            }
          });
        }
      } );

      $('#ToolTables_table_id_2').click( function () {
        if(!$('#ToolTables_table_id_2').hasClass('DTTT_disabled')) {
          $('#confirm').dialog({
          width: 300,
          closeText: "",
          modal: true,
          resizable: false,
          title: "Are you sure?",
          buttons: [
            {
              text: "Ok",
              click: function() {
                $('#confirm' ).dialog( "close" );
                $.ajax({
                  method: 'post',
                  url: "#{delete_department_path}",
                  data: {id: table.row('.selected').data()[0]},
                  success: function() {
                    window.location.replace("#{departments_path}" + '?page=' + table.page());
                  }
                });
              }
            },
            {
              text: "Cancel",
              click: function() {
                $('#confirm' ).dialog( "close" );
              }
            }
            ]
          });
        }
      });
    });

app/views/admin/ticket_statuses.html.haml
%div{:class => 'well centered'}
  %h1 Ticket Statuses
  %br
  #table{:style => 'border-radius: 25px; padding: 20px; background: #B8E6B8;'}
    %table{:id => "table_id", :class => "display"}
      %thead
        %tr
          %th ID
          %th Ticket status
      %tbody
        -@ticket_statuses.each do |t_s|
          %tr
            %td= t_s[:id]
            %td= t_s[:title]

#dialog{:style => 'display: none; text-align: center'}
  #title_label
  = label_tag 'Title:'
  %br
  = text_field_tag 'title', '', {:size => '30'}


#confirm{:style => 'display: none; text-align: center'}
  #message Delete ticket status?
#error{:style => 'display: none; text-align: center'}
  #message

:javascript
    $(document).ready( function () {
      $.fn.dataTable.TableTools.defaults.aButtons = [ "div", "div", "div" ];

      var table = $("#table_id").DataTable({
        "aLengthMenu": [5, 10, 15],
        "iDisplayLength": 5,
        "columnDefs": [
          {
              "targets": [0],
              "visible": false
          }
        ],
        "order": [[ 1, "asc" ]],
        "sDom": 'T<"clear">lfrtip',
        "oTableTools": {
            "aButtons": [
                {
                    "sExtends":    "div",
                    "sButtonText": "New ticket status"
                },
                {
                    "sExtends":    "div",
                    "sButtonText": "Edit ticket status"
                },
                {
                    "sExtends":    "div",
                    "sButtonText": "Delete ticket status"
                }
            ]
        }
      });

      table.page(parseInt("#{params[:page] || 0}")).draw(false);

      $('#ToolTables_table_id_1').addClass('DTTT_disabled');
      $('#ToolTables_table_id_2').addClass('DTTT_disabled');

      $('#table_id tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
            $('#ToolTables_table_id_1').addClass('DTTT_disabled');
            $('#ToolTables_table_id_2').addClass('DTTT_disabled');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
            $('#ToolTables_table_id_1').removeClass('DTTT_disabled');
            $('#ToolTables_table_id_2').removeClass('DTTT_disabled');
        }
      } );

      $('#ToolTables_table_id_0').click( function () {
        $('#dialog').dialog({
          width: 370,
          closeText: "",
          modal: true,
          resizable: false,
          title: "New ticket status",
          buttons: [
            {
              text: "Create",
              click: function() {
                $.ajax({
                  method: 'POST',
                  url: "#{create_ticket_status_path}",
                  data: {title: $('#title').val()},
                  success: function() {
                    $('#dialog' ).dialog( "close" );
                    window.location.replace("#{ticket_statuses_path}" + '?page=' + table.page());
                  }
                });
              }
            },
            {
              text: "Cancel",
              click: function() {
                $('#dialog' ).dialog( "close" );
              }
            }
          ]
        });
      } );

      $('#ToolTables_table_id_1').click( function () {
        if(!$('#ToolTables_table_id_1').hasClass('DTTT_disabled')) {
          $.ajax({
            method: 'get',
            url: "#{get_ticket_status_path}",
            data: {id: table.row('.selected').data()[0]},
            success: function(json) {
              var data = JSON.parse(json);
              $('#title').val(data.title);
              $('#dialog').dialog({
                width: 370,
                closeText: "",
                modal: true,
                resizable: false,
                title: "Edit ticket status",
                buttons: [
                  {
                    text: "Save",
                    click: function() {
                      $.ajax({
                        method: 'POST',
                        url: "#{edit_ticket_status_path}",
                        data: {id: data.id, title: $('#title').val()},
                        success: function() {
                          $('#dialog' ).dialog( "close" );
                          window.location.replace("#{ticket_statuses_path}" + '?page=' + table.page());
                        }
                      });
                    }
                  },
                  {
                    text: "Cancel",
                    click: function() {
                      $('#dialog' ).dialog( "close" );
                    }
                  }
                ]
              });
            }
          });
        }
      } );

      $('#ToolTables_table_id_2').click( function () {
        if(!$('#ToolTables_table_id_2').hasClass('DTTT_disabled')) {
          $('#confirm').dialog({
          width: 300,
          closeText: "",
          modal: true,
          resizable: false,
          title: "Are you sure?",
          buttons: [
            {
              text: "Ok",
              click: function() {
                $('#confirm' ).dialog( "close" );
                $.ajax({
                  method: 'post',
                  url: "#{delete_ticket_status_path}",
                  data: {id: table.row('.selected').data()[0]},
                  success: function() {
                    window.location.replace("#{ticket_statuses_path}" + '?page=' + table.page());
                  }
                });
              }
            },
            {
              text: "Cancel",
              click: function() {
                $('#confirm' ).dialog( "close" );
              }
            }
            ]
          });
        }
      });
    });

app/views/admin/tickets.html.haml
%div{:class => 'well centered'}
  %h1 Tickets
  %br
  #tabs
    %ul
      %li
        = link_to "All tickets", raw(url_for(:controller => 'admin', :action => 'tickets_list_partial', :page => params[:page], :id => 0))
      -TicketStatus.all.each do |status|
        %li
          = link_to status.title, raw(url_for(:controller => 'admin', :action => 'tickets_list_partial', :page => params[:page], :id => status.id))


:javascript
  $(document).ready( function () {
    $("#tabs").tabs();

  } );

app/views/admin/tickets_list_partial.html.haml
#table{:style => 'border-radius: 25px; padding: 20px; background: #B8E6B8;'}
  %table{:id => "table_id#{@status_id.nil? ? '' : @status_id}", :class => "display"}
    %thead
      %tr
        %th ID
        %th Reference
        %th Department
        %th Status
        %th Creator_name
        %th Creator_email
    %tbody
      -@tickets.each do |ticket|
        %tr
          %td= ticket[:id]
          %td= link_to ticket[:reference], ticket_path(:reference => ticket[:reference])
          %td= ticket[:department]
          %td= ticket[:status]
          %td= ticket[:creator_name]
          %td= ticket[:creator_email]

:javascript
    $(document).ready( function () {
      var array = [0];
      if("#{User.current.department_id}" != "") array[1] = 2;
      $("#table_id#{@status_id.nil? ? '' : @status_id}").DataTable({
        "aLengthMenu": [5, 10, 15],
        "iDisplayLength": 5,
        "order": [[ 1, "asc" ]],
        "bDestroy": true,
        "columnDefs": [
          {
              "targets": array,
              "visible": false
          }
          ]
        });
    });

app/views/admin/users.html.haml
%div{:class => 'well centered'}
  %h1 Users
  %br
  #table{:style => 'border-radius: 25px; padding: 20px; background: #B8E6B8;'}
    %table{:id => "table_id", :class => "display"}
      %thead
        %tr
          %th ID
          %th User name
          %th Login
          %th Department
          %th Admin
      %tbody
        -@users.each do |user|
          %tr
            %td= user[:id]
            %td= user[:username]
            %td= user[:login]
            %td= user[:department]
            %td= user[:admin]

#dialog{:style => 'display: none; text-align: center'}
  #login_label
  = label_tag 'Login:'
  %br
  = text_field_tag 'login', '', {:size => '30'}
  #username_label
  = label_tag 'User name:'
  = text_field_tag 'username', '', {:size => '30'}
  #department_label
  = label_tag 'Department:'
  = select_tag 'departments', options_for_select(@departments, 0), :style => "width: 80%", :include_blank => true
  #admin_label
  = label_tag 'Admin:'
  = check_box_tag 'admin'
  #password_label
    = label_tag 'password:'
  = text_field_tag 'password', '', {:size => '30'}

#confirm{:style => 'display: none; text-align: center'}
  #message Delete user?
#error{:style => 'display: none; text-align: center'}
  #message

:javascript
    $(document).ready( function () {
      $.fn.dataTable.TableTools.defaults.aButtons = [ "div", "div", "div" ];

      var table = $("#table_id").DataTable({
        "aLengthMenu": [5, 10, 15],
        "iDisplayLength": 5,
        "columnDefs": [
          {
              "targets": [0],
              "visible": false
          }
        ],
        "order": [[ 1, "asc" ]],
        "sDom": 'T<"clear">lfrtip',
        "oTableTools": {
            "aButtons": [
                {
                    "sExtends":    "div",
                    "sButtonText": "New user"
                },
                {
                    "sExtends":    "div",
                    "sButtonText": "Edit user"
                },
                {
                    "sExtends":    "div",
                    "sButtonText": "Delete user"
                }
            ]
        }
      });

      table.page(parseInt("#{params[:page] || 0}")).draw(false);

      $('#ToolTables_table_id_1').addClass('DTTT_disabled');
      $('#ToolTables_table_id_2').addClass('DTTT_disabled');

      $('#table_id tbody').on( 'click', 'tr', function () {
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
            $('#ToolTables_table_id_1').addClass('DTTT_disabled');
            $('#ToolTables_table_id_2').addClass('DTTT_disabled');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
            $('#ToolTables_table_id_1').removeClass('DTTT_disabled');
            $('#ToolTables_table_id_2').removeClass('DTTT_disabled');
        }
      } );

      $('#ToolTables_table_id_0').click( function () {
        $('#dialog').dialog({
          width: 370,
          closeText: "",
          modal: true,
          resizable: false,
          title: "New user",
          buttons: [
            {
              text: "Create",
              click: function() {
                var checked = $('#admin').prop('checked');
                $.ajax({
                  method: 'POST',
                  url: "#{create_user_path}",
                  data: {login: $('#login').val(), username: $('#username').val(), departments: $('#departments').val(),
                         password: $('#password').val(), admin: checked},
                  success: function() {
                    $('#dialog' ).dialog( "close" );
                    window.location.replace("#{users_path}" + '?page=' + table.page());
                  }
                });
              }
            }
          ]
        });
      } );

      $('#ToolTables_table_id_1').click( function () {
        if(!$('#ToolTables_table_id_1').hasClass('DTTT_disabled')) {
          $.ajax({
            method: 'get',
            url: "#{get_user_path}",
            data: {id: table.row('.selected').data()[0]},
            success: function(json) {
              var data = JSON.parse(json);
              $('#login').val(data.login);
              $('#username').val(data.username);
              $('#departments').val(data.department_id);
              $('#password').val(data.password);
              if(data.admin == true) {
                $('#admin').prop("checked", true);
              } else {
                $('#admin').prop("checked", false);
              }
              $('#dialog').dialog({
                width: 370,
                closeText: "",
                modal: true,
                resizable: false,
                title: "Edit user",
                buttons: [
                  {
                    text: "Save",
                    click: function() {
                      var checked = $('#admin').prop('checked');
                      $.ajax({
                        method: 'POST',
                        url: "#{edit_user_path}",
                        data: {id: data.id, login: $('#login').val(), username: $('#username').val(), departments: $('#departments').val(),
                               password: $('#password').val(), admin: checked},
                        success: function() {
                          $('#dialog' ).dialog( "close" );
                          window.location.replace("#{users_path}" + '?page=' + table.page());
                        }
                      });
                    }
                  }
                ]
              });
            }
          });
        }
      } );

      $('#ToolTables_table_id_2').click( function () {
        if(!$('#ToolTables_table_id_2').hasClass('DTTT_disabled')) {
          $('#confirm').dialog({
          width: 300,
          closeText: "",
          modal: true,
          resizable: false,
          title: "Are you sure?",
          buttons: [
            {
              text: "Ok",
              click: function() {
                $('#confirm' ).dialog( "close" );
                $.ajax({
                  method: 'post',
                  url: "#{delete_user_path}",
                  data: {id: table.row('.selected').data()[0]},
                  success: function() {
                    window.location.replace("#{users_path}" + '?page=' + table.page());
                  }
                });
              }
            },
            {
              text: "Cancel",
              click: function() {
                $('#confirm' ).dialog( "close" );
              }
            }
            ]
          });
        }
      });
    });