config/routes.rb
Rails.application.routes.draw do
  root :to => 'ticket#index'

  resources :admin, :ticket
  post "create_ticket_post" => "ticket#create_ticket_post"
  get "search_ticket" => "ticket#search_ticket"
  get "ticket" => "ticket#ticket"
  post "ticket_add_message_post" => "ticket#ticket_add_message_post"
  post "get_ownership" => "ticket#get_ownership"
  get "admin" => "admin#admin"
  post "log_in_post" => "admin#log_in_post"
  get "tickets" => "admin#tickets"
  post "log_out_post" => "admin#log_out_post"
  get "get_json_tickets" => "admin#get_json_tickets"
  get "tickets_list_partial" => "admin#tickets_list_partial"

  get "users" => "admin#users"
  post "create_user" => "admin#create_user"
  get "get_user" => "admin#get_user"
  post "edit_user" => "admin#edit_user"
  post "delete_user" => "admin#delete_user"

  get "departments" => "admin#departments"
  post "create_department" => "admin#create_department"
  get "get_department" => "admin#get_department"
  post "edit_department" => "admin#edit_department"
  post "delete_department" => "admin#delete_department"

  get "ticket_statuses" => "admin#ticket_statuses"
  post "create_ticket_status" => "admin#create_ticket_status"
  get "get_ticket_status" => "admin#get_ticket_status"
  post "edit_ticket_status" => "admin#edit_ticket_status"
  post "delete_ticket_status" => "admin#delete_ticket_status"
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :ticket_messages, :inverse_of => :ticket
  belongs_to :department
  belongs_to :ticket_status

  after_create :assign_reference
  after_create :send_mail, unless: :skip_callbacks

  private
  def assign_reference
    strs = []
    3.times do |i|
      strs[i] = ('A'..'Z').to_a.shuffle[0,3].join
    end
    start_string = "%06d" % self.id
    middle = start_string.length/2
    first_hex = "%02X" % start_string.slice(0, middle)
    last_hex = "%02X" % start_string.slice(middle, start_string.size)
    self.update_column(:title, "#{strs[0]}-#{first_hex}-#{strs[1]}-#{last_hex}-#{strs[2]}")
  end

  def send_mail
    CustomerMailSender.ticket_created_mail(self.creator_name, self.creator_email, self.title).deliver
  end
end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
  def index
    @departments = []
    Department.all.each do |dep|
      @departments << [dep.title, dep.id]
    end
  end

  def create_ticket_post
    wait_for_staff_status = TicketStatus.where(title: 'Waiting for Staff Response').first.try(:id)
    if params[:departments].blank? || params[:name].blank? || params[:email].blank?
      flash[:danger] = "Fill in all fields please!"
      redirect_to root_path and return
    else
      ticket = Ticket.create!(department_id: params[:departments], ticket_status_id: wait_for_staff_status,
                              creator_name: params[:name], creator_email: params[:email])
      if ticket
        TicketMessage.create!(ticket_id: ticket.id, text: params[:text])
        redirect_to ticket_path :reference => ticket.title
      else
        flash[:danger] = "Something went wrong!"
        redirect_to root_path and return
      end
    end
  end

  def search_ticket
    ticket = Ticket.where(title: params[:ticket_reference]).first
    if ticket
      redirect_to ticket_path :reference => params[:ticket_reference]
    else
      flash[:danger] = "Ticket with given reference is not exists!"
      redirect_to root_path and return
    end
  end

  def ticket
    @ticket = Ticket.joins(:ticket_messages).where(title: params[:reference]).first
    @statuses = []
    TicketStatus.all.each do |t_s|
      @statuses << [t_s.title, t_s.id]
    end
  end

  def ticket_add_message_post
    if params[:ticket_message].blank?
      flash[:info] = 'Blank message. Please fill in the field.'
      redirect_to ticket_path :reference => params[:ticket_reference]
    else
      ticket = Ticket.where(title: params[:ticket_reference]).first
      if ticket
        if User.current
          if params[:ticket_status].to_i != 0
            begin
              ticket.ticket_status_id = params[:ticket_status].to_i
              ticket.save!
              CustomerMailSender.ticket_change_mail(ticket.creator_name, ticket.creator_email, ticket.title).deliver
            rescue Exception => e
              flash[:danger] = e
              redirect_to ticket_path :reference => params[:ticket_reference] and return
            end
          else
            flash[:danger] = "Something went wrong! Message does not saved!"
            redirect_to ticket_path :reference => params[:ticket_reference] and return
          end
        else
          begin
            wait_for_staff_status = TicketStatus.where(title: 'Waiting for Staff Response').first.try(:id)
            wait_for_customer_status = TicketStatus.where(title: 'Waiting for Customer').first.try(:id)
            if ticket.ticket_status_id == wait_for_customer_status
              ticket.ticket_status_id = wait_for_staff_status
              ticket.save!
            end
          rescue Exception => e
            flash[:danger] = e
            redirect_to ticket_path :reference => params[:ticket_reference] and return
          end
        end
        begin
          message = TicketMessage.new(text: params[:ticket_message], ticket_id: ticket.id)
          message.user_id = session[:user].to_i if session[:user] && session[:user].to_i != 0
          message.save!
        rescue Exception => e
          flash[:danger] = e
          redirect_to ticket_path :reference => params[:ticket_reference] and return
        end
        redirect_to ticket_path :reference => params[:ticket_reference] and return
      else
        flash[:danger] = "Something went wrong! Ticket not found"
        redirect_to root_path and return
      end
    end
  end

  def get_ownership
    ticket = Ticket.where(id: params[:ticket_id]).first
    if ticket
      begin
        ticket.user_id = params[:user_id].to_i
        ticket.skip_callbacks = true
        ticket.save!
      rescue Exception => e
        flash[:danger] = e
        redirect_to tickets_path and return
      end
    end
    redirect_to ticket_path :reference => params[:ticket_reference] and return
  end
end

app/views/ticket/index.html.haml
%div{:class => 'well centered', :style => 'width: 500px; background: #B8E6B8;'}
  = form_tag create_ticket_post_path, :method => :post do
    #name_label
      = label_tag 'Name:'
    #name
      = text_field_tag 'name', '',{:placeholder => 'Joe'}
    %br
    #email_label
      = label_tag 'Email:'
    #email
      = email_field_tag 'email', '',{:placeholder => 'email@example.com'}
    %br
    #department_label
      = label_tag 'Department:'
    #department
      = select_tag 'departments', options_for_select(@departments, 0)
    #text_area_label
      = label_tag 'Your request:'
    #text
      = text_area_tag 'text', '', :size => "40x4"
      %br
      %br
      = submit_tag 'Create issue ticket', :class => 'btn btn-success'

app/views/ticket/ticket.html.haml
%div{:class => 'well centered', :style => 'height: auto; text-align: center; background: #33AD33;'}
  %p{:style => 'color:brown; font-size: 150%; font-weight: bold;'}= "Ticket #{@ticket.title}"
  %div{:style => 'width: 100%'}
    = label_tag 'Created by:', nil, :style=> 'float: left;'
    %div{:style => 'color:brown; font-size: 110%; float: left; width: 45%; text-align: left;'}= @ticket.creator_name
    %div{:style => 'color:brown; font-size: 110%; float: right;'}= TicketStatus.where(id:@ticket.ticket_status_id).first.try(:title)
    = label_tag 'Ticket status:', nil, :style=> 'float: right; width: 20%; text-align: right;'
  %div{:style => 'width: 100%; text-align: left; display:inline-block;'}
    = label_tag 'Ticket department:', nil, :style => 'float: left;'
    %div{:style => 'color:brown; font-size: 110%; width: 50%; float: left;'}= Department.where(id: @ticket.department_id).first.try(:title)
    - if session[:user] && @ticket.user_id.nil?
      = button_to "Get ownership", {:controller => :ticket, :action => 'get_ownership', :ticket_id => @ticket.id,
                                    :user_id => session[:user], :ticket_reference => @ticket.title},
                                    :class => 'btn btn-warning', :style => 'float: right'
  %div{:style => 'display:inline-block; height:100%; vertical-align:middle; overflow-y: scroll; height:175px;'}
    - @ticket.ticket_messages.order('created_at asc').each do |message|
      %div{:style => 'text-align: left; border-radius: 15px 15px 15px; padding: 5px; margin-bottom: 5px; background: lightgreen;'}
        = label_tag 'Creator:'
        - if message.user_id
          = User.where(id: message.user_id).first.try(:username)
        - else
          Customer
        = label_tag 'Created:'
        = message.created_at.strftime("%d/%m/%Y %H:%M:%S")
        %br
        #center{:style => 'text-align: center'}
          = text_area_tag "message_#{message.id}", message.text, :size => '115x4', :disabled => true
        #right{:style => 'text-align: right; margin-right: 10px'}
          %button{:class => 'quote btn btn-warning', :id => "#{message.id}"} Quote
%br
- if (session[:user] && @ticket.user_id == User.current.id) || session[:user].nil?
  #new_message{:class => 'well centered', :style => "text-align: left ; margin: auto; background: #{session[:user].nil? ? '#A3FFD1' : '#ADD633'};"}
    = form_tag ticket_add_message_post_path, :method => :post do
      #container{:style => 'width: 100%'}
        = label_tag 'Type answer here:', nil, :style=> 'width: 45%; float: left;'
        - if session[:user]
          = select_tag 'ticket_status', options_for_select(@statuses, @ticket.ticket_status_id), :style=> 'width: 20%; float: right;'
          = label_tag 'Set status:', nil, :style=> 'width: 15%; float: right; text-align: right;'
      #center{:style => 'text-align: center'}
        = text_area_tag 'ticket_message', '', :size => '115x4', :style => 'float: center'
      = text_field_tag 'ticket_reference', @ticket.title , {:hidden => true}
      = submit_tag 'Add answer', :class => 'btn btn-success', data: {:disable_with => '...'}, :style => 'margin-top: 3px;'

:javascript
  $( document ).ready(function() {
   $('.quote').click(function(event) {
    $('#ticket_message').val($('#ticket_message').val() + 'quote------->\n' + $('#message_' +this.id).val() + '\n--------------<\n')
   });
  });