config/routes.rb
Rails.application.routes.draw do
  root :to => 'ticket#index'

  resources :admin, :ticket
  post "create_ticket_post" => "ticket#create_ticket_post"
  get "search_ticket" => "ticket#search_ticket"
  get "ticket" => "ticket#ticket"
  post "ticket_add_message_post" => "ticket#ticket_add_message_post"
  post "get_ownership" => "ticket#get_ownership"
  get "admin" => "admin#admin"
  post "log_in_post" => "admin#log_in_post"
  get "tickets" => "admin#tickets"
  post "log_out_post" => "admin#log_out_post"
  get "get_json_tickets" => "admin#get_json_tickets"
  get "tickets_list_partial" => "admin#tickets_list_partial"

  get "users" => "admin#users"
  post "create_user" => "admin#create_user"
  get "get_user" => "admin#get_user"
  post "edit_user" => "admin#edit_user"
  post "delete_user" => "admin#delete_user"

  get "departments" => "admin#departments"
  post "create_department" => "admin#create_department"
  get "get_department" => "admin#get_department"
  post "edit_department" => "admin#edit_department"
  post "delete_department" => "admin#delete_department"

  get "ticket_statuses" => "admin#ticket_statuses"
  post "create_ticket_status" => "admin#create_ticket_status"
  get "get_ticket_status" => "admin#get_ticket_status"
  post "edit_ticket_status" => "admin#edit_ticket_status"
  post "delete_ticket_status" => "admin#delete_ticket_status"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SupportIssueTracking
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav{:class => 'navbar navbar-default', :style => 'background: #33AD33;'}
      .container-fluid
        %a{:class => "navbar-brand", :style => 'color: #993300;', :href => root_path, :title => 'To start page.'} Support Issue Tracking
        =form_tag search_ticket_path, :class => "navbar-form navbar-right", :role => "search" , :method => :get do
          .form-group
            = text_field_tag 'ticket_reference', '',{:placeholder => 'Type ticket reference here...', :size => "23"}
          = submit_tag 'Search', :class => "btn btn-primary"
        - if User.current
          %ul{:class => "nav navbar-nav"}
            %li{:class => "active"}
              %a{:href => tickets_path}= User.current.username
            - if User.current.admin
              %li
                %a{:href => users_path, :style => "color: #003366"} Users
              %li
                %a{:href => departments_path, :style => "color: #003366"} Departments
              %li
                %a{:href => ticket_statuses_path, :style => "color: #003366"} Ticket Statuses
          =form_tag log_out_post_path, :class => "navbar-form navbar-right", :method => :post do
            = submit_tag 'Log out', :class => "btn btn-info"
    - unless flash.empty?
      - flash.each do |key, value|
        %div{:class => "centered-top alert alert-#{key}", :style => 'width: 50%'}
          %a{:class => "close", "data-dismiss" => "alert"} &#215;
          = content_tag :div, value, :id => "flash_#{key}", :style => "text-align:center"
        %br
    = yield